Ha 20 clientes
Maria vai atender Desmond Hume (108)
Joao vai atender Shannon Rutherford (1)
Maria vai atender Richard Alpert (91)
Maria vai atender Jacob (74)
Maria vai atender Sun Paik (63)
Joao vai atender Kate Austen (2)
Joao vai atender John Locke (4)
Maria vai atender Charlie Pace (52)
Joao vai atender Hugo Reyes (8)
Maria vai atender Kwon (42)
Maria vai atender Charles Widmore (38)
Joao vai atender Analucia Cortez (13)
Joao vai atender James Ford (15)
Maria vai atender Claire Littleton (32)
Maria vai atender Charlotte Lewis (31)
Maria vai atender Daniel Faraday (29)
Joao vai atender Sayid Jarrah (16)
Maria vai atender Jack Shephard (23)
Ha 2 clientes
Maria vai atender Danielle Rousseau (18)
Joao vai atender Benjamin Linus (17)
Escritorio vazio
